import type { ContestPreview } from "@/types/domain";

// Demo seed for Sprint 1 UI only. The Radar list must be replaced by Supabase reads.
export const demoContests: ContestPreview[] = [
  {
    id: "demo-anapolis-administrativo",
    title: "Prefeitura de Anápolis - Administrativo",
    organization: "Prefeitura Municipal de Anápolis",
    city: "Anápolis",
    state: "GO",
    status: "open",
    roles: ["Assistente administrativo", "Fiscal", "Técnico"],
    educationLevel: "medio",
    salaryText: "R$ 2.100 a R$ 4.200",
    registrationEndLabel: "30/06/2026",
    officialUrl: "https://example.com/edital-demo",
    matchScore: 92,
    matchReason: "Ensino médio, área administrativa e distância compatíveis.",
  },
  {
    id: "demo-aparecida-saude",
    title: "Processo seletivo municipal - Saúde",
    organization: "Secretaria Municipal de Saúde",
    city: "Aparecida de Goiânia",
    state: "GO",
    status: "open",
    roles: ["Agente comunitário", "Técnico em enfermagem"],
    educationLevel: "tecnico",
    salaryText: "R$ 1.900 a R$ 3.300",
    registrationEndLabel: "18/07/2026",
    officialUrl: "https://example.com/edital-demo",
    matchScore: 84,
    matchReason: "Área de saúde e cidade dentro do raio configurado.",
  },
  {
    id: "demo-camara-goiania",
    title: "Câmara Municipal - Vagas técnicas",
    organization: "Câmara Municipal de Goiânia",
    city: "Goiânia",
    state: "GO",
    status: "upcoming",
    roles: ["Técnico legislativo", "Analista"],
    educationLevel: "superior",
    salaryText: "Não informado",
    registrationEndLabel: "não informado",
    officialUrl: "https://example.com/edital-demo",
    matchScore: 71,
    matchReason: "Cargo similar aos interesses, mas dados de inscrição ainda incompletos.",
  },
];
