/// <reference types="next" />
/// <reference types="next/image-types/global" />

// This file is generated by Next.js in normal project scaffolds.
// Keep it committed so typechecking works before the first dev run.
